export const EducationLabels = [
  {
    label: "College/University",
    name: "collegeOrUniversity",
    type: "text",
    required: true,
    value: "",
  },
  {
    label: "Start Date",
    name: "startDate",
    type: "date",
    required: true,
    value: "",
  },
  {
    label: "End Date",
    name: "endDate",
    type: "date",
    required: true,
    value: "",
  },
  {
    label: "Qualification",
    name: "qualification",
    type: "text",
    required: true,
    value: "",
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    required: false,
    value: "",
  },
  {
    label: "School",
    name: "School",
    type: "text",
    required: true,
    value: "",
  },
  {
    label: "Start Date",
    name: "startDate",
    type: "date",
    required: true,
    value: "",
  },
  {
    label: "End Date",
    name: "endDate",
    type: "date",
    required: true,
    value: "",
  },
  {
    label: "Qualification",
    name: "qualification",
    type: "text",
    required: true,
    value: "",
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    required: false,
    value: "",
  },
];
